# Generated by Django 4.1.7 on 2024-03-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(max_length=150)),
                ('doctorname', models.CharField(max_length=150)),
                ('dob', models.CharField(max_length=150)),
                ('symptoms', models.CharField(max_length=150)),
            ],
        ),
    ]
